import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Add funds presents invoice-first auto detection, safe estimate and explicit multi-chain method selection', () => {
  const page = read('app/(app)/user/add-funds/page.tsx')
  const form = read('components/payment-forms.tsx')
  assert.match(page, /How adding funds works/)
  assert.match(page, /Copy your payment details/)
  assert.match(page, /exact amount, address and QR/)
  assert.match(page, /watchableRoute\(gateway\)/)
  assert.match(page, /paste a transaction ID only if the payment is not detected/)
  assert.doesNotMatch(page, /Add credit in four clear steps|Send and paste ID|Automatic verification ready/)
  assert.doesNotMatch(page, /Never reuse a transaction ID/)
  assert.doesNotMatch(page, /wallet password, private key, seed phrase/)
  assert.match(form, /QUICK_AMOUNTS = \[10, 25, 50, 100\]/)
  assert.match(form, /Estimated request total/)
  assert.match(form, /Do not send this estimate/)
  assert.match(form, /automaticVerification \? 'Auto detection' : 'Manual review'/)
  assert.match(form, /Continue to payment details/)
  assert.doesNotMatch(form, /Suggested amount to send|<span className="badge badge--success">Auto verification/)
  assert.match(form, /verified on-chain amount determines the credit/i)
  assert.match(form, /Binance-issued pegged representation/)
  assert.match(form, /createInvoiceAction/)
  assert.doesNotMatch(form, /Creating a payment request does not move money/)
  assert.doesNotMatch(form, /private key or seed phrase/)
})

test('invoice page uses per-route explorer metadata and refreshes database state only', () => {
  const page = read('app/(app)/user/invoice/[reference]/page.tsx')
  const actions = read('components/invoice-actions.tsx')
  const form = read('components/payment-forms.tsx')
  assert.match(page, /paymentAddressQrDataUrl/)
  assert.match(page, /AutoRefreshPaymentStatus/)
  assert.match(page, /paymentTransactionUrl/)
  assert.doesNotMatch(page, /https:\/\/bscscan\.com\/tx\//)
  assert.match(actions, /router\.refresh\(\)/)
  assert.match(actions, /5_000/)
  assert.doesNotMatch(actions, /fetch\(/)
  assert.match(form, /chainKind: 'evm' \| 'tron'/)
  assert.match(form, /\[a-fA-F0-9\]\{64\}/)
  assert.match(form, /0x\[a-fA-F0-9\]\{64\}/)
})

test('uncoded legacy invoice explains manual-only status and safe way to request automatic detection', () => {
  const page = read('app/(app)/user/invoice/[reference]/page.tsx')
  assert.match(page, /Manual verification required/)
  assert.match(page, /This request has no unique payment code/)
  assert.match(page, /It may have been created before automatic detection was enabled/)
  assert.match(page, /If you already paid, paste the transaction ID below/)
  assert.match(page, /choose a different amount or network to start a new request/)
  assert.match(page, /Choosing the same amount and network reopens this pending request/)
  assert.match(page, /href="\/user\/add-funds"/)
  assert.doesNotMatch(page, /Send supported USDT, then paste your transaction hash/)
})

test('fractional withdrawal fees never imply automatic credit without the invoice code', () => {
  const invoice = read('app/(app)/user/invoice/[reference]/page.tsx')
  const watcher = read('lib/payment-watcher.ts')
  const panel = read('app/(app)/admin/page.tsx')
  const association = read('components/admin-unmatched-transfers.tsx')
  const approval = read('components/admin-invoice-review.tsx')
  assert.match(invoice, /amount the recipient will receive after any exchange withdrawal fee/)
  assert.match(invoice, /If the fee changes them, paste your transaction ID below for administrator review/)
  assert.match(invoice, /manual credit uses the verified amount/)
  assert.match(watcher, /feeShortfallCandidates\(candidate\)/)
  assert.match(watcher, /another request after withdrawal fees/)
  assert.match(panel, /Unmatched transfers — manual payment check/)
  assert.match(association, /Verify &amp; associate/)
  assert.match(approval, /Confirm manual payment &amp; credit/)
  assert.match(approval, /\/api\/admin\/invoice-verifications/)
  assert.doesNotMatch(invoice, /short still counts in full/)
})

test('bounded payment reconciliation runs inside the existing provider poll entrypoint', () => {
  const script = read('scripts/poll-provider-jobs.ts')
  assert.match(script, /pollInvoiceVerifications/)
  assert.match(script, /const payments = await pollInvoiceVerifications\(boundedLimit\)/)
  assert.doesNotMatch(script, /setInterval|setTimeout/)
})

test('admin fallback uses API guard, admin RBAC, reason, idempotency and route-specific explorer links', () => {
  const route = read('app/api/admin/invoice-verifications/route.ts')
  const component = read('components/admin-invoice-review.tsx')
  const domain = read('lib/payment-verification.ts')
  assert.match(route, /guard\(request\)/)
  assert.match(route, /hasAdminRole\(found\.user\)/)
  assert.match(component, /csrfToken/)
  assert.match(component, /idempotencyKey/)
  assert.match(component, /Decision reason/)
  assert.match(component, /explorer_url/)
  assert.doesNotMatch(component, /https:\/\/bscscan\.com\/tx\//)
  assert.match(domain, /consumeAttempt\('admin-invoice-verification'/)
  assert.match(domain, /credit\(row\.user_id, approvedCreditCents, 'topup', 'invoice'/)
})

test('payment verification is fail closed and delegates chain reads to server-side adapters', () => {
  const config = read('lib/payment-config.ts')
  const provider = read('lib/payment-chain-provider.ts')
  const domain = read('lib/payment-verification.ts')
  assert.match(config, /IUNLOCKMOBILE_TOPUP_ENABLED/)
  assert.match(config, /PAYMENT_ROUTE_DEFINITIONS/)
  assert.match(config, /IUNLOCKMOBILE_TOPUP_TRC20_USDT_ENABLED/)
  assert.match(config, /IUNLOCKMOBILE_TOPUP_BEP20_BSC_USD_ENABLED/)
  assert.match(config, /IUNLOCKMOBILE_TOPUP_ERC20_USDT_ENABLED/)
  assert.match(provider, /eth_chainId/)
  assert.match(provider, /eth_getTransactionReceipt/)
  assert.match(provider, /eth_blockNumber/)
  assert.match(provider, /wallet\/gettransactioninfobyid/)
  assert.match(provider, /walletsolidity\/getnowblock/)
  assert.match(provider, /TRON-PRO-API-KEY/)
  assert.match(domain, /payment_route_snapshot_mismatch/)
  assert.match(domain, /log\.contractAddress !== snapshottedContract/)
  assert.match(domain, /topicAddress\(log\.topics\[2\]\) !== destination/)
  assert.match(domain, /rawAmountToCreditCents\(candidate\.rawAmount/)
  assert.match(domain, /requestedCreditCents/)
  assert.match(domain, /verifiedCreditCents/)
  assert.match(domain, /duplicate_transaction/)
})

test('payments are detected without a pasted hash, and pasting stays as the fallback', () => {
  const script = read('scripts/poll-provider-jobs.ts')
  const page = read('app/(app)/user/invoice/[reference]/page.tsx')
  const actions = read('components/invoice-actions.tsx')
  assert.match(script, /const watcher = await scanPaymentWallets\(\)/)
  assert.ok(script.indexOf('scanPaymentWallets()') < script.indexOf('pollInvoiceVerifications(boundedLimit)'))
  assert.match(page, /nudgeInvoicePayment\(invoice\.reference\)/)
  assert.match(page, /<CodedAmount/)
  assert.match(page, /className="paste-fallback"/)
  assert.match(page, /PaymentReferenceForm/)
  assert.doesNotMatch(actions, /fetch\(/)
})
